### ISSUE TITLE
Link to install usercss appointing another repo

### ISSUE THREAD

**Issue by erickmajor** [StylishThemes/GitHub-Community-Dark#1]
Hi,

The link in identified for text **Install the usercss**, in [README.md](https://github.com/StylishThemes/GitHub-Community-Dark/blob/master/README.md) appointing to another repository, the _Wikipedia dark user_ script.

Hope this helps

* **Browser**: Google Chrome 67
* **Operating System**: Windows 7 64 bits
* **Screenshot**: [screenshot](https://github.com/erickmajor/evidence-of-issues/blob/master/ScreenHunter_%2020180724%2011.47.05.jpg)

**Comment by Mottie** [comment]
Hi @erickmajor!

Oops, yeah thanks for letting us know!

**Comment by the-j0k3r** [comment]
@erickmajor on my next update I will also fix the userCSS update url with same issue.

for time being you can manually replace it in user css

https://raw.githubusercontent.com/StylishThemes/GitHub-Community-Dark/master/github-community-dark.user.css

**Comment by the-j0k3r** [comment]
So in order for you to fix your automatic updates just make your local style look like https://github.com/StylishThemes/GitHub-Community-Dark/commit/8e32f73985d239421fd1bddea5a306b380d83b79

Its should be OK from 0.1.4 onward

**Comment by erickmajor** [comment]
Thanks @the-j0k3r ,
Works properly!
