### ISSUE TITLE
Subscribe to our Newsletter is white

### ISSUE THREAD

**Issue by armano2** [StylishThemes/GitHub-Community-Dark#3]
* **Browser**: Chrome
* **Operating System**: win 10
* **Screenshot**:
![image](https://user-images.githubusercontent.com/625469/48303901-e3ddc700-e510-11e8-94da-1392d472001c.png)
![image](https://user-images.githubusercontent.com/625469/48303906-f48e3d00-e510-11e8-9353-1c4d43ee5abd.png)
![image](https://user-images.githubusercontent.com/625469/48303908-fa841e00-e510-11e8-9548-1b70239b0e1b.png)

* **HTML of the section where the issue occurs**:
````html
<a href="http://eepurl.com/dDFH4f" class="featured-event mb-4 text-center" style="align-items: center; display: flex; border: 1px solid #d1d5da; border-radius: 3px; justify-content: center; padding:10px; text-decoration: none; width: 100%; target=" _blank"="">
<img src="https://dyjpb62732.i.lithium.com/html/assets/mail.svg?E40C5167F5D10E6EE0D67B77DCFBC5E3" style="height:30px;"><h2 style="font-size:18px;font-weight:300;margin-bottom:0px;margin-left:10px">Subscribe to our Newsletter</h2>
</a>
````

**Comment by Mottie** [comment]
Hi @armano2!

Thanks for letting us know!
