### ISSUE TITLE
MOVED TO DISCOURSE - This style is no longer needed

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Community-Dark#9]
As of today the community site is now running Discourse so we no longer have to maintain a separate style just for it.

https://github.blog/2020-05-27-the-github-support-community-has-a-new-look-and-feel/

Ref: https://github.com/StylishThemes/Discourse-Dark/issues/34

**Comment by the-j0k3r** [comment]
There was nothing wrong with the old. Though less one style to maintain.

Go for archiving

**Comment by the-j0k3r** [comment]
OK after https://github.com/StylishThemes/GitHub-Community-Dark/commit/d3a32e8a64eb0c6a16fd93917a9502e7de8b4e8c users will receive 1.0.0 update and see

![Capture](https://user-images.githubusercontent.com/31389848/85227074-3cf32980-b3db-11ea-94aa-a7e2186cdb48.PNG)

@silverwind please also archive this style please.
